// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemWspomagania.API.Data;

namespace SystemWspomagania.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191219155016_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("SystemWspomagania.API.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameCompany")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhoneNr")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("SystemWspomagania.API.Models.IssueWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateIssue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateReturn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stan")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeaponId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WeaponId");

                    b.ToTable("IssueWeapons");
                });

            modelBuilder.Entity("SystemWspomagania.API.Models.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Annotation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateLeave")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateReturn")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Typ")
                        .HasColumnType("TEXT");

                    b.Property<string>("Where")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("SystemWspomagania.API.Models.Soldier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<long>("Pesel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhoneNr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("Usersurname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Soldiers");
                });

            modelBuilder.Entity("SystemWspomagania.API.Models.Weapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seria")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("SystemWspomagania.API.Models.IssueWeapon", b =>
                {
                    b.HasOne("SystemWspomagania.API.Models.Weapon", "Weapon")
                        .WithMany("IssueWeapons")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SystemWspomagania.API.Models.Leave", b =>
                {
                    b.HasOne("SystemWspomagania.API.Models.Soldier", "Soldier")
                        .WithMany("Leaves")
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SystemWspomagania.API.Models.Soldier", b =>
                {
                    b.HasOne("SystemWspomagania.API.Models.Company", "Company")
                        .WithMany("Soldiers")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("SystemWspomagania.API.Models.Weapon", b =>
                {
                    b.HasOne("SystemWspomagania.API.Models.Soldier", "Soldier")
                        .WithMany("Weapons")
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
